# Generated by Django 4.2.3 on 2023-07-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessstreak',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
